### PR TITLE
Added Aoi - docs , doc searcher + 1 snippet for test purposes

### PR DESCRIPTION
**Pull request by Whirl21**
Uhm before you commit this to the main extension please try it once!

### CODE REVIEW

**Comment by Darkempire78** [comment]
You ahve to use a new file for the aoi snippets

**Comment by Darkempire78** [comment]
You can also use snippet's variable to replace things as "token" by `${NUMBEROFTHEVARIABLE:TEXT}`
For example : `{0:Token}`

**Comment by Darkempire78** [comment]
@Whirl21 ?

**Comment by Whirl21** [comment]
imao i forgot about this i'll redo the commit

**Pull request closed without merging**
